#Model Config
backbone: ResNet50
batch-size: 32
epoch: 20
learning-rate: 0.001
scale-l2-regularizer: 0.01
dropout-rate: 0.5
experiment: 'Baseline'

#Database Config
train-path: 'E:\Projeto-FaceRecognition\face_recognition\dataset\icbrw_ProbeImages_mtcnn_224'
validation-path: 'E:\Projeto-FaceRecognition\face_recognition\dataset\icbrw_ProbeImages_mtcnn_224'
inputSize: 112
lfw-callback: 'E:\Projeto-FaceRecognition\face_recognition\dataset\lfw_aligned_mtcnn_224/'
lfw-callback-pairs: 'E:\Projeto-FaceRecognition\face_recognition\dataset\lfw_aligned_mtcnn_224\originalPairs.txt'

#Test Config
dataset-name: 'ICBRW' # 'ICBRW' 'LFW'
model-weights-path: 'E:\Projeto-FaceRecognition\face_recognition\checkpoints\Align\weights_12.h5' #'E:\Projeto-FaceRecognition\face_recognition\checkpoints\Align\weights_12.h5'
test-path: 'E:\Projeto-FaceRecognition\face_recognition\dataset\icbrw_ProbeImages_mtcnn_224' #'C:\Users\bruno\Desktop\Universidade_3Ano_2Semestre\Projeto\FaceRecognition\Dataset\icbrw_Data_Cropped\icbrw_ProbeImages\'
pairs-path: 'E:\Projeto-FaceRecognition\face_recognition\dataset\icbrw_ProbeImages_mtcnn_224\pairs.txt'
test-type: 'Align-L2-CosineSim' #'Align'; 'Align-L2'; 'Align-L2-CosineSim'; 'Baseline'

#Prepare Data Config
database-path: ''
destination-path: ''

#Create Pairs ICBRW
dataset-local: 'E:\Projeto-FaceRecognition\face_recognition\dataset\icbrw_ProbeImages_mtcnn_224\'
pairs-local: 'E:\Projeto-FaceRecognition\face_recognition\dataset\icbrw_ProbeImages_mtcnn_224\pairs.txt'


#Evaluations results
evaluation-data: 'E:\Projeto-FaceRecognition\face_recognition\evaluationsResult\ICBRW\Align-L2-CosineSim\10062022_1608\Align-L2-CosineSim.npz'
model-data: 'E:\Projeto-FaceRecognition\face_recognition\checkpoints\Baseline\history.npy'

